on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Dev Provision
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_MARIADB_PASSWORD: ${{ secrets.AZURE_MARIADB_PASSWORD}}
          AZURE_FQDN: ${{ secrets.AZURE_FQDN}}
          AZURE_APPLICATION_NAME: ${{ secrets.AZURE_APPLICATION_NAME}}
          AZURE_USE_CERTIFICATE: ${{ secrets.AZURE_USE_CERTIFICATE}}
          AZURE_DEPLOY_JUMPHOST: ${{ secrets.AZURE_DEPLOY_JUMPHOST}}
          AZURE_ADMIN_USERNAME: ${{ secrets.AZURE_ADMIN_USERNAME}}
          AZURE_ADMIN_PASSWORD: ${{ secrets.AZURE_ADMIN_PASSWORD}}